import React  from 'react'

export default function About() {
 
  return (
    <div>
     Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic laudantium, aspernatur sed voluptatibus totam ipsam cupiditate. Earum neque accusamus, ducimus vel eveniet similique autem repellendus molestias, illo corporis nemo, consequuntur sed distinctio nobis in debitis culpa obcaecati temporibus? Placeat impedit rem eum libero vero alias quos illo magnam! Provident recusandae temporibus accusamus itaque quasi! Voluptates accusamus voluptate earum necessitatibus expedita? Quia, eum vel. Pariatur perferendis natus ipsa fugiat quos sint tempore. Molestias, laudantium facilis distinctio cupiditate voluptates, ducimus alias provident itaque dolorum delectus enim fuga, numquam similique earum! Maiores unde aliquam earum, porro ratione vero quod fugiat suscipit molestias amet veritatis ducimus ex, quo inventore quis eius alias esse! Nihil omnis, cupiditate repellat dolorum alias temporibus inventore quam perspiciatis. Quos sit sint impedit commodi omnis, doloremque eveniet amet voluptatem laborum architecto harum ad aliquid nostrum placeat consequuntur magnam ipsa tempora dolor dolore exercitationem aspernatur perferendis ex! Ad voluptatem, laborum voluptate, corrupti unde, consequuntur consequatur possimus porro expedita ullam incidunt nulla blanditiis iste vero culpa magnam et suscipit? Enim, assumenda doloribus saepe nesciunt distinctio commodi non similique, porro reprehenderit voluptates, voluptatum rem fuga culpa ex maiores magnam aliquam facilis ipsam cupiditate tempora! Animi necessitatibus officiis quis a beatae nisi nesciunt aliquid quod! Beatae suscipit illum cupiditate temporibus, similique culpa, nobis deleniti porro, numquam harum doloremque eum a iusto recusandae quibusdam totam sapiente neque odio modi cumque consequuntur consectetur natus! Debitis vitae similique, placeat repellat molestias labore nulla quos? Saepe ipsum, laudantium a modi culpa corrupti consequuntur iste quod velit excepturi deleniti voluptatibus molestias incidunt? Repellendus ab officia minima blanditiis, nam, voluptatum at pariatur iusto non velit cumque itaque, quia illo! Sequi ipsa minima cum sed commodi beatae aperiam maiores animi exercitationem obcaecati voluptas repellat et expedita, nisi autem ipsam odio sit corporis. Deserunt illo corporis exercitationem esse, cum commodi velit eum?
    </div>
  )
}
